import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Search, Plus, Box } from 'lucide-react';
import { useApp } from '../App';
// Runtime-константы
import { ProductType } from '../services/types';
const ProductsPage = () => {
    const { products, addToCart } = useApp();
    const [searchTerm, setSearchTerm] = useState('');
    const filteredProducts = products.filter(p => p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (p.id && p.id.toLowerCase().includes(searchTerm.toLowerCase())));
    const handleAddToCart = (product) => {
        addToCart(product, 1);
    };
    const formatPrice = (price) => price.toLocaleString('ru-RU');
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-black text-black uppercase tracking-tight", children: "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u0442\u043E\u0432\u0430\u0440\u043E\u0432" }), _jsx("p", { className: "text-black font-semibold text-lg", children: "\u041F\u0440\u043E\u0434\u0430\u0436\u0430 \u0440\u0430\u0437\u0440\u0435\u0448\u0435\u043D\u0430 \u0434\u0430\u0436\u0435 \u043F\u0440\u0438 \u043D\u0443\u043B\u0435\u0432\u043E\u043C \u043E\u0441\u0442\u0430\u0442\u043A\u0435." })] }), _jsxs("div", { className: "relative w-full md:w-96", children: [_jsx(Search, { className: "absolute left-4 top-1/2 -translate-y-1/2 text-black", size: 20 }), _jsx("input", { type: "text", placeholder: "\u041F\u043E\u0438\u0441\u043A \u043F\u043E \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u044E...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full pl-12 pr-4 py-4 bg-white border-2 border-black rounded-[1.5rem] shadow-sm focus:border-indigo-600 outline-none font-black text-black" })] })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6", children: filteredProducts.map(product => {
                    return (_jsx("div", { className: "bg-white rounded-[2.5rem] border-2 border-slate-200 hover:border-indigo-600 shadow-md hover:shadow-2xl transition-all flex flex-col group overflow-hidden", children: _jsxs("div", { className: "p-7 flex-1 flex flex-col", children: [_jsxs("div", { className: "flex items-start justify-between mb-3", children: [_jsx("h3", { className: "font-black text-black text-xl uppercase leading-tight line-clamp-2 group-hover:text-indigo-700 transition-colors", children: product.name }), _jsx("span", { className: `text-[10px] px-3 py-1 rounded-full font-black uppercase tracking-widest ${product.type === ProductType.WEIGHT ? 'bg-orange-100 text-orange-700' : product.type === ProductType.BOXED ? 'bg-indigo-100 text-indigo-700' : 'bg-blue-100 text-blue-700'}`, children: product.type === ProductType.WEIGHT ? 'Кг' : product.type === ProductType.BOXED ? 'Кор' : 'Шт' })] }), _jsxs("div", { className: "space-y-2 mb-6", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Box, { size: 16, className: "text-black" }), _jsxs("span", { className: "text-sm font-black uppercase tracking-widest text-black", children: ["\u041D\u0430 \u0441\u043A\u043B\u0430\u0434\u0435: ", _jsxs("span", { className: product.stock <= 0 ? 'text-rose-600 underline' : 'text-black', children: [product.stock, " ", product.type === ProductType.WEIGHT ? 'кг' : product.type === ProductType.BOXED ? 'кор' : 'шт'] })] })] }), product.type === ProductType.BOXED && (_jsxs("p", { className: "text-xs font-black text-indigo-700 uppercase ml-6 italic", children: ["\u0412\u0435\u0441 \u043A\u043E\u0440: ", product.weightPerBox, " \u043A\u0433"] }))] }), _jsxs("div", { className: "mt-auto pt-5 border-t-2 border-slate-100 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1", children: "\u0426\u0435\u043D\u0430 \u043F\u0440\u043E\u0434\u0430\u0436\u0438" }), _jsxs("p", { className: "text-2xl font-black text-black tracking-tighter", children: [formatPrice(product.price), " ", _jsx("span", { className: "text-xs font-bold", children: "\u0441\u0443\u043C" })] })] }), _jsx("button", { onClick: () => handleAddToCart(product), className: "w-14 h-14 rounded-2xl flex items-center justify-center transition-all bg-indigo-600 text-white shadow-lg hover:scale-110 active:scale-95", children: _jsx(Plus, { size: 32, strokeWidth: 4 }) })] })] }) }, product.id));
                }) })] }));
};
export default ProductsPage;
